require('dotenv').config();
const { generateMnemonic, mnemonicToSeed } = require("bip39-light");
const { hdkey } = require('ethereumjs-wallet');
const { ethers } = require("ethers");
const { PRIVATE_KEY } = process.env;

// works for eth and polygon
const ethereumPath = "m/44'/60'/0'/0/0";

// the address of the UBQFitCoin contract generated by the deploy.js script
const ubqFitCoinAddress = "0x0a30d5ec621f1c74e8c1175b1aa3500e794cc4af";

// the wallet where the contract was deployed
const ubqFitWalletAddress = "0x53dfd4581d64ef84f98236914014393b734be0ce";


const createWallet = (mnemonic) => {
    mnemonic = generateMnemonic(128);
    console.log("mnemonic:", mnemonic);
    const hdwallet = hdkey.fromMasterSeed(mnemonicToSeed(mnemonic));
    const wallet = hdwallet.derivePath(ethereumPath).getWallet();
    console.log("privateKey:", wallet.getPrivateKeyString());
    console.log("address:", wallet.getAddressString());
    return wallet;
};

const main = async () => {

    const receiverWallet = createWallet();

    // A Web3Provider wraps a standard Web3 provider, which is
    // what MetaMask injects as window.ethereum into each page
    //const provider = new ethers.providers.Web3Provider(window.ethereum)

    // MetaMask requires requesting permission to connect users accounts
    //await provider.send("eth_requestAccounts", []);

    // The provider also allows signing transactions to
    // send ether and pay to change state within the blockchain.
    // For this, we need the account signer...
    //const signer = provider.getSigner();

    // If you don't specify a //url//, Ethers connects to the default 
    // (i.e. ``http:/\/localhost:8545``)
    const provider = new ethers.providers.JsonRpcProvider({
        url: "https://rpc-mumbai.maticvigil.com"
     });
    
    const signer = new ethers.Wallet(PRIVATE_KEY, provider);

    const ubqFitCoinContract = new ethers.Contract(ubqFitCoinAddress, ubqFitCoinAbi, provider);

    balance = await ubqFitCoinContract.balanceOf(ubqFitWalletAddress, 0);

    console.log("UBQFit wallet balance:" + balance);

    const ubqFitCoinContractWriter = ubqFitCoinContract.connect(signer);

    const amountToTransfer = 1;

    const tx = await ubqFitCoinContractWriter.safeTransferFrom(ubqFitWalletAddress, receiverWallet.getAddressString(), 0, amountToTransfer, 0);
    
    console.log("tx:", tx.hash);

    // check the balance of the receiver wallet
    // setTimeout(async () => {
    //     balance = await ubqFitCoinContract.balanceOf(receiverWallet.getAddressString(), 0);
    //     console.log("Receiver wallet balance:" + balance);
    // }, 5000);
    
}

const ubqFitCoinAbi = [
    "function balanceOf(address account, uint256 tokenId) view returns (uint256)",
    "function safeTransferFrom(address from, address to, uint256 tokenId, uint256 amount, bytes calldata data) external"
];

main()
    .catch((error) => {
    console.error(error)
    process.exit(1)
});
  